# Generated by Django 3.1.3 on 2022-12-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securityapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guard',
            name='pic',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
