# Generated by Django 3.1.3 on 2022-12-20 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('securityapp', '0007_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='mobilenumber',
            new_name='mobileno',
        ),
    ]
