# Generated by Django 3.1.3 on 2022-12-23 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('securityapp', '0015_auto_20221223_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='mobilenum',
            new_name='mobile',
        ),
    ]
