# Generated by Django 3.1.3 on 2022-12-24 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('securityapp', '0017_booking_guard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackinghistory',
            name='guard',
        ),
    ]
