# Generated by Django 3.1.3 on 2022-12-26 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('securityapp', '0022_booking_guardname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='guardname',
        ),
    ]
